### PR TITLE
Add pg and mysql testing

### PR DESCRIPTION
**Pull request by abinoam**
See: https://docs.travis-ci.com/user/database-setup/#using-ruby

### CODE REVIEW

**Comment by abinoam** [comment]
cc: #6

**Comment by abinoam** [comment]
Main notes:
- Database configurations will be load from `spec/database.yml`
- We default to `sqlite3` but can test against another adapter using `$QUANTUM_FIELDS_DB_ADAPTER` environment variable
- Travis is now set to test against the sqlite3, postgresql and mysql2
- When running specs we're gonna echo what adapter is being used to easy future debugging
- Bundler caching is enabled at travis for faster builds

**Comment by abinoam** [comment]
@ErvalhouS could review it?

**Review by ErvalhouS — APPROVED** [review]
Awesome work

**Pull request merged**
